# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.6  

    - name: Create a temporary artifact downloads folder for graphs
      run: mkdir graphs       

    - name: Install Python pandas
      run: python -m pip install --upgrade pip pandas
          
    - name: Install Python matplotlib
      run: python -m pip install --upgrade pip matplotlib  
         
    - name: Install email
      run: sudo apt-get install mailutils        
      
    - name: Install Python pyinstaller
      run: python -m pip install --upgrade pip datetime

    - name: Install Python datetime
      run: pip install pyinstaller   

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore           
      
    - name: run
      run: dotnet run --project ConsoleApp1/ConsoleApp1.csproj
      
    - name: run python 
      run: python TestModel/testGraph/testGraph/testGraph.py     
      
    - name: send a graph 
      run:  mail -s "Graph" -A testplot.png super.kydryavuy2011@yandex.ru
     

    - name: artifact      
      uses: actions/upload-artifact@v3
      with:
        title: my-artifacts
          - files: graphs/testplot.png
          
    - name: moving artfact to temp folder
      run: |
        mv testplot.png graphs   

    # - name: Upload build
      # uses: actions/upload-artifact@master
      # with:
        # name: tesplotopener
        # path: graphs/testplot.png
        # env-url: FOOBAR
    # - name: Use URL for something
      # run: echo "${{ env.FOOBAR }}" >> $GITHUB_STEP_SUMMARY

    # - name: HTML Preview
      # id: html_preview
      # uses: pavi2410/html-preview-action@v2
      # with:
        # html_file: 'index.html'

          
    # - name: Step 3 - Use the Upload Artifact GitHub Action   
      # run: |
        # echo "![alt text]($HOME/graphs/testplot.png)" >> $GITHUB_STEP_SUMMARY
        # echo "$HOME" >> $GITHUB_STEP_SUMMARY
        # ls $HOME
     
    
