
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source   
      
    environment:
      name: github-pages
      url: ${{ steps.change-page-url.outputs.new_page_url }}   
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.6  

    - name: Create a temporary artifact downloads folder for graphs
      run: mkdir graphs       

    - name: Install Python pandas
      run: python -m pip install --upgrade pip pandas
          
    - name: Install Python matplotlib
      run: python -m pip install --upgrade pip matplotlib  
         
    # - name: Install email
      # run: sudo apt-get install mailutils        
      
    - name: Install Python pyinstaller
      run: python -m pip install --upgrade pip datetime

    - name: Install Python datetime
      run: pip install pyinstaller   

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore           
      
    - name: run
      run: dotnet run --project ConsoleApp1/ConsoleApp1.csproj
      
    - name: run python 
      run: python TestModel/testGraph/testGraph/testGraph.py     
      
    # - name: send a graph 
      # run:  mail -s "Graph" -A testplots.webp super.kydryavuy2011@yandex.ru
      
    - name: moving artfact to temp folder
      run: |
        mv testplots.webp graphs         
           
    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: folder for graphs
        path: graphs

    - name: Deploy 🚀
      uses: actions/upload-pages-artifact@v2
      with:
        path: graphs # The folder the action should deploy.

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
      
    - name: Override page_url
      id: change-page-url
      run: echo "new_page_url=${{ steps.deployment.outputs.page_url }}TestModel/index.html" >> $GITHUB_OUTPUT    

      
    - name: find index
      run: find . -type f -name "*.html"                       
    
    - name: Step 3 - Use the Upload Artifact GitHub Action   
      run: |
        echo "![alt text](../../graphs/testplots.webp)" >> $GITHUB_STEP_SUMMARY
        echo "$HOME" >> $GITHUB_STEP_SUMMARY
               
     
    
