# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.5 
         
    - name: Install Python pandas
      run: python -m pip install --upgrade pip pandas
      
    - name: Install Python matplotlib
      run: python -m pip install --upgrade pip matplotlib  
      
    - name: Install Python pathlib
      run: python -m pip install --upgrade pip pathlib       
      
    - name: Install Python datetime
      run: python -m pip install --upgrade pip datetime         
        
        
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: show folder 
      run: ls         
      
      
    # - name: run
      # run: dotnet run --project ConsoleApp1/ConsoleApp1.csproj