# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.5 
         
    - name: Install Python pandas
      run: python -m pip install --upgrade pip pandas
      
    - name: Install Python matplotlib
      run: python -m pip install --upgrade pip matplotlib  
         
    # was a vonflict with a pyinstaller,pretty funny
    # - name: Install Python pathlib
      # run: python -m pip install --upgrade pip pathlib       
      
    - name: Install Python pyinstaller
      run: python -m pip install --upgrade pip datetime

    - name: Install Python datetime
      run: pip install pyinstaller      
        
               
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    #probably will not need it in the end, but leave it for a moment
    # - name: publish ubuntu
      # run: dotnet publish -c Release -r ubuntu.16.10-x64
      
    - name: create exec 
      run: pyinstaller --onefile TestModel/testGraph/testGraph/testGraph.py 
        
    - name: show folder 
      run: ls
      
    - name: show folder dist
      run: ls dist     
      
    - name: show testgraph 
      run: ls dist/testGraph

    - name: find file 
      run: find . -name '*.exe'            
      
    - name: give permission 
      run: chmod +x TestModel/testGraph/testGraph/testEnvironment/Scripts/python.exe       
      
    - name: run
      run: dotnet run --project ConsoleApp1/ConsoleApp1.csproj
      
    # - name: execute python script
      # run: python TestModel/testGraph/testGraph/testEnvironment/Scripts/python.exe