# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.5  

    - name: install -y xvfb
      run: sudo apt-get install -y xvfb

    - name: browser
      run: sudo update-alternatives --config x-www-browser


    - name: Install
      run: sudo apt-get install x11vnc xvfb fluxbox

    - name: export
      run: export DISPLAY=:0
      
      
    - name: snap remove firefox
      run: sudo apt-get install firefox

    - name: goggle
      run: |
        Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=:99
        firefox TestModel/index.html   

    # - name: Install
      # run: sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
      
    # - name: Install
      # run: sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable     
                     
    # - name: goggle
      # run: |
        # Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=127.0.0.1:10.0
        # google-chrome TestModel/index.html   

    # - name: open
      # run: firefox TestModel/index.html
   
    # - name: browser
      # run: xdg-settings set default-web-browser google-chrome-stable
    
      
    # - name: browser
      # run: xdg-settings get default-web-browser

 
    # - name: Install Python pandas
      # run: python -m pip install --upgrade pip pandas
          
    # - name: Install Python matplotlib
      # run: python -m pip install --upgrade pip matplotlib  
         
    # - name: Install email
      # run: sudo apt-get install mailutils        
      
    # - name: Install Python pyinstaller
      # run: python -m pip install --upgrade pip datetime

    # - name: Install Python datetime
      # run: pip install pyinstaller   

    # - name: Restore dependencies
      # run: dotnet restore
    # - name: Build
      # run: dotnet build --no-restore           
      
    # - name: run
      # run: dotnet run --project ConsoleApp1/ConsoleApp1.csproj
      
    # - name: run python 
      # run: python TestModel/testGraph/testGraph/testGraph.py     
      
    # - name: send a graph 
      # run:  mail -s "Graph" -A testplot.png super.kydryavuy2011@yandex.ru
      
      

      



    # - name: browser
      # run: xdg-open TestModel/index.html
      
      
      
      
    # - name: HTML Preview
      # id: html_preview
      # uses: pavi2410/html-preview-action@v2
      # with:
        # html_file: 'TestModel/index.html'
        # url: steps.html_preview.outputs.url